language: node_js
node_js:
    - node
cache:
    directories:
        - node_modules
script: yarn install
before_deploy: yarn add now --no-save
deploy:
    - provider: script
      script: now --public --token $NOW_TOKEN && now alias --token $NOW_TOKEN
      skip_cleanup: true
