language: node_js
node_js:
    - node
cache:
    directories:
        - node_modules
script: yarn install
before_deploy: yarn add now --no-save
deploy:
    - provider: script
      script: now --public --token $NOW_TOKEN -e SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY -e ACCESS_KEY_ID=$ACCESS_KEY_ID -e TES=$TES && now alias --token $NOW_TOKEN -e SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY -e ACCESS_KEY_ID=$ACCESS_KEY_ID -e TES=$TES
      skip_cleanup: true
